spring:
  application:
    name: cooking
  datasource:
    url: jdbc:mysql://localhost:3306/cooking?characterEncoding=utf-8&serverTimezone=Asia/Shanghai&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: 123456

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

app:
  data-initializer:
    enabled: false

server:
  port: 8080
